# Generated by Django 5.2.12 on 2026-04-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'Учитель'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='teacher', max_length=20),
        ),
    ]
