# Generated by Django 5.2.12 on 2026-04-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_result_first_name_result_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='category',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('pre_intermediate', 'Pre-intermediate'), ('intermediate', 'Intermediate'), ('upper_intermediate', 'Upper-intermediate'), ('oge', 'OGE'), ('ege', 'EGE'), ('grammar', 'Grammar'), ('veretchagina', 'Veretchagina'), ('afanaseva', 'Afanaseva')], max_length=50, null=True),
        ),
    ]
