# Generated by Django 5.2.12 on 2026-04-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
