# Generated by Django 5.2.12 on 2026-04-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_test_last_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#e0e0e0', max_length=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='category',
        ),
        migrations.AddField(
            model_name='test',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tests.tag'),
        ),
    ]
